version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: propertyuser
      POSTGRES_PASSWORD: propertypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:              # ✅ add redis_data volume
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:             # ✅ add here

